import type { Metadata } from "next";
import "./globals.css";
import LayoutDsk from "@/components/Desktop/LayoutDsk/LayoutDsk";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
} >) {
  return (
    <html dir="rtl">
      <body className="">
       <LayoutDsk >
        {children}
       </LayoutDsk>
      </body>
    </html>
  );
}
