import type { Metadata } from "next";
import "./globals.css";
import LayoutDsk from "@/components/Desktop/LayoutDsk/LayoutDsk";
import IsLoginProvider from "@/context/provider/IsLogProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
} >) {
  return (
    <html dir="rtl">
      <body className="">
        <IsLoginProvider>
       <LayoutDsk >
        {children}
       </LayoutDsk>
        </IsLoginProvider>
      </body>
    </html>
  );
}
